const signals = [
  {id:"01",instrument:"南航转债",code:"110075 · 可转债",event:"临近到期",aiDecision:"research",aiLabel:"建议研究",confidence:"中等置信",summary:"页面价格106.35元接近税前赎回价106.50元，表面上是小幅下行、保留正股弹性的结构。",caution:"个人投资者可能需对利息部分缴税，社区测算税后回收约105.20元；“最多亏1.5元”并不严谨。",data:"现价 106.35 · 税前赎回 106.50 · 最后交易日 10-09",source:"https://app.jisilu.cn/question/522483?gopage-true__page-1__item_id=5518045",sourceLabel:"集思录原帖",official:"",tag:"临期转债"},
  {id:"02",instrument:"洽洽转债",code:"128135 · 可转债",event:"临近到期",aiDecision:"watch",aiLabel:"建议观察",confidence:"中等置信",summary:"价格114.785元接近115元税前赎回价，但转股价值仅34.49元，向上期权非常弱。",caution:"需要确认利息税后的实际回收额；如果税后低于买入价，结构可能只是确定小亏且几乎没有上行。",data:"现价 114.785 · 税前赎回 115.00 · 最后交易日 10-14",source:"https://app.jisilu.cn/question/524995",sourceLabel:"9月4日投资提示",official:"",tag:"临期转债"},
  {id:"03",instrument:"晶能转债",code:"118034 · 可转债",event:"下修到底",aiDecision:"watch",aiLabel:"建议观察",confidence:"中等置信",summary:"转股价由6.35元降至4.36元，9月7日生效，属于已经落地的明确事件。",caution:"下修本身不是本金保护。需要补齐新转股价值、复牌价格、溢价率和发行人信用后才能判断。",data:"新转股价 4.36 · 9月7日生效",source:"https://app.jisilu.cn/question/524566",sourceLabel:"集思录讨论",official:"https://static.cninfo.com.cn/finalpage/2026-09-04/1225547209.PDF",tag:"转债下修"},
  {id:"04",instrument:"芳源转债",code:"118020 · 可转债",event:"再次提议下修",aiDecision:"watch",aiLabel:"建议观察",confidence:"较高置信",summary:"转股价此前已由18.63元两次下修至9元，董事会再次提议下修，股东会尚未表决。",caution:"集思录估算下修到底后仍有约29%溢价；即使下修通过，也未自然形成低风险收益。",data:"当前转股价 9.00 · 股东会 09-11 · 估算到底溢价 29.02%",source:"https://app.jisilu.cn/question/524995",sourceLabel:"9月4日投资提示",official:"https://static.cninfo.com.cn/finalpage/2026-09-04/1225545926.PDF",tag:"转债下修"},
  {id:"05",instrument:"优彩资源 / 优彩转债",code:"002998 / 127078",event:"筹划控制权变更",aiDecision:"research",aiLabel:"建议研究",confidence:"中等置信",summary:"这是可能扩展策略边界的新事件：控制权变化或影响正股，并可能传导至关联转债。",caution:"协议尚未签署且可能终止。控制权变更不等于触发要约，需要等待受让方、比例和交易方式。",data:"9月4日起停牌 · 预计不超过2个交易日",source:"https://app.jisilu.cn/question/524995",sourceLabel:"集思录汇总",official:"https://static.cninfo.com.cn/finalpage/2026-09-04/1225547328.PDF",tag:"控制权变更"},
  {id:"06",instrument:"创金合信北京国资公司REIT",code:"公募REIT",event:"上市大幅破发",aiDecision:"watch",aiLabel:"策略层观察",confidence:"中等置信",summary:"社区称认购中签率约80%、开盘跌约25%，暴露高比例中签与高发行定价叠加的非对称风险。",caution:"这不是当前套利机会，更像发行申购策略的失败样本；社区数字仍需以基金公告和行情核实。",data:"社区描述：中签约80% · 开盘跌约25%",source:"https://app.jisilu.cn/question/524995",sourceLabel:"集思录原帖",official:"",tag:"REITs发行"},
  {id:"07",instrument:"公募基金披露规则",code:"ETF / LOF",event:"十大持有人数据减少",aiDecision:"watch",aiLabel:"系统情报",confidence:"较低置信",summary:"帖子称公募基金不再继续披露十大持有人，可能影响ETF、LOF套利的拥挤度与持有人结构判断。",caution:"目前只有社区讨论，尚未核实正式规则和适用范围；它影响研究能力，不是直接交易机会。",data:"最新回复 09-04 14:29",source:"https://app.jisilu.cn/question/524925?show_all_answer-TRUE__item_id-5534477__answer_id-5534477__single-TRUE=",sourceLabel:"具体讨论与回复",official:"",tag:"系统情报"},
  {id:"08",instrument:"AI高股息轮动",code:"A股策略",event:"自动化选股实践",aiDecision:"reject",aiLabel:"暂不纳入",confidence:"较高置信",summary:"低估值、高股息与门票股轮动可能偏低波，但它不是严格的套利或事件驱动。",caution:"是否纳入取决于系统边界：只做套利，还是扩大到所有低风险策略。",data:"最新回复 09-04 15:13",source:"https://app.jisilu.cn/question/524983",sourceLabel:"集思录原帖",official:"",tag:"策略边界"},
  {id:"09",instrument:"可转债调仓记录",code:"可转债组合",event:"高抛低吸与做T",aiDecision:"reject",aiLabel:"建议排除",confidence:"较高置信",summary:"帖子主要记录转债仓位、市场情绪、高抛低吸和做T，没有发现明确事件或退出权。",caution:"日内操作与临时判断还可能触碰“盘中不决策”的交易纪律。",data:"最新回复 09-04 14:44",source:"https://app.jisilu.cn/question/524999",sourceLabel:"集思录原帖",official:"",tag:"日常交易"}
];

const decisionOptions=[["research","重点研究"],["watch","继续观察"],["reject","排除"],["unclear","暂时说不清"]];
const reasonOptions=["未选择原因","没有下行锚","上行空间不足","信用风险太大","时间过长","交易摩擦太大","信息不足","直觉上有意思","不属于套利范围"];
const knownReviews={
  "01":{decision:"research",note:"值得进一步核查临期回收与向上空间。"},
  "02":{decision:"research",note:"值得进一步研究。"},
  "03":{decision:"reject",note:"下修到底本身不构成低风险套利；还需结合提议、表决、最终下修价格及其他下行保护。"},
  "04":{decision:"research",note:"可能存在机会；不怎么回撤是重要条件。低评级若赔率足够高也可以研究。"},
  "05":{decision:"watch",note:"需要先看公告内容再决定。"},
  "06":{decision:"reject",note:"作为反面案例：不能把REITs打新天然视为低风险。"},
  "07":{decision:"reject",note:"没有实际影响。"},
  "08":{decision:"reject",note:"不是套利，不关注。"},
  "09":{decision:"reject",note:"每日调仓记录不是具体标的机会。"}
};
const storageKey="arbitrage-review-2026-09-04-v2";
const caseStorageKey="arbitrage-case-feedback-round-2-v2";
let reviews={...knownReviews,...loadJson(storageKey)};
const knownCaseReviews={"05":{verdict:"disagree",view:"优彩转债价格160+、转股溢价率15%+，防守很难，没有继续研究的必要。"}};
let caseReviews={...knownCaseReviews,...loadJson(caseStorageKey)};
let activeFilter="all";

const casePlans=[
  {id:"01",stage:"研究初稿已发布",kind:"临期转债",brief:"核实个人投资者税后兑付金额、最后交易与转股时点、正股弹性和真实最大损失。",questions:["税后实际回收额","剩余资金占用天数与年化","转股价值与向上空间","流动性及退出方式"],research:{verdict:"当前价不通过",tone:"negative",asOf:"行情截至 2026-09-04 收盘",thesis:"它不是“转股溢价几乎为0”的临期转债。按个人投资者105.20元的常见沪市税后估算，当前买入并持有到期约亏1.08%；公司又已明确到期前即使再次触发也不下修。右尾只来自正股在约40天内上涨约30%，因此最可能路径是小亏，而不是大概率不亏。",metrics:[["现价","106.35元"],["到期税前","106.50元"],["个人税后估算","105.20元*"],["静态损失","-1.15元 / -1.08%"],["转股价值","约81.52元"],["转股溢价","30.45%"]],facts:["最后交易日为10月9日；10月12日至14日停止交易但仍可转股；10月15日兑付。","转股价6.17元，正股5.03元；转股价值约81.52元。要让转股价值追上106.35元，正股需到约6.56元。","7月10日董事会明确：从7月13日至10月14日，即使再次触发下修条件，也不提出下修方案。","截至2026年3月末未转股余额约58.96亿元，债项市场资料显示AAA。"],scenarios:[["大概率路径","正股未涨约30%","持有到期；按105.20元估算亏约1.08%，另有资金占用与交易费用。"],["中间路径","到期前在二级市场卖出","损益取决于市场价格；这不是合同保证的退出价。"],["小概率右尾","正股升至约6.56元以上","转股价值开始超过当前买价；再往上才有真正的权益弹性。"]],trigger:"个人账户只有当成交价显著低于最终确认的税后兑付净额，并留出手续费与口径误差，才进入‘本金锚＋免费远端期权’观察区。",uncertainty:"*公司到期公告只披露106.50元含税价，尚未披露个人实发额。105.20元来自按106.50−100全额作为利息计税的沪市惯例讨论，必须在最终扣税说明或券商确认后才能当作硬数字。",sources:[["公司到期兑付公告","https://big5.sse.com.cn/site/cht/www.sse.com.cn/disclosure/listedinfo/announcement/c/new/2026-09-04/600029_20260904_8AG4.pdf"],["公司不下修公告","https://file.finance.sina.com.cn/211.154.219.97%3A9494/MRGG/CNSESH_STOCK/2026/2026-7/2026-07-11/12440307.PDF"],["9月4日行情快照","https://quote.cfi.cn/quote112404_110075.html"],["集思录税务争议原帖","https://www.jisilu.cn/question/522483?gopage-true__page-1__item_id=5518045"]]}},
  {id:"02",stage:"研究初稿已发布",kind:"临期转债",brief:"判断这是否只是接近确定的小亏，还是存在尚未识别的向上权利。",questions:["税后实际回收额","到期与交易时间轴","极低转股价值的影响","是否存在其他事件催化"],research:{verdict:"更接近现金替代，不是正偏",tone:"neutral",asOf:"行情截至 2026-09-04 收盘",thesis:"洽洽的下行比南航更窄，但右侧几乎不存在。参照同类深市到期案例，只对最后一期2%票息扣20%个税时，个人净兑付约114.60元，较现价114.78元仅低0.18元；但转股溢价232.85%，约46天内正股需要上涨约237%才触及转换盈亏平衡。它可研究为临期现金替代，却不符合“低回撤＋不确定上行”的首选结构。",metrics:[["现价","114.78元"],["到期税前","115.00元"],["个人净额推算","114.60元*"],["静态损失","-0.18元 / -0.16%"],["转股价值","约34.48元"],["转股溢价","232.85%"]],facts:["最后交易日为10月14日；10月15日至19日停止交易但仍可转股；10月19日到期。","募集说明书约定到期按面值115%（含最后一期利息）赎回，第六年票息2%。","截至2026年6月末未转股余额13.398亿元，几乎全部尚未转股；公司无担保，主体及债项评级AA、展望稳定。","同期公司货币资金约23.01亿元、交易性金融资产约18.43亿元；这改善兑付判断，但不等于无信用风险。"],scenarios:[["大概率路径","正常兑付、按推算扣税","个人约收114.60元，较现价亏约0.16%，尚未计费用。"],["机构路径","不由发行人代扣个人税","税前兑付115元，毛收益约0.19%；需按自身税务与会计口径核算。"],["极小概率右尾","正股由约18.7元升至约63.1元","转换价值才追上当前债价；在剩余期限内基本不能把它当有效期权。"]],trigger:"个人账户的观察买价应低于最终公告确认的个人实发净额，并扣除手续费和安全垫；若只追求正偏，它即使跌到该阈值也只是一笔低风险carry，不是优先级最高的机会。",uncertainty:"*洽洽尚未发布最终到期兑付及扣税公告。114.60元是依据115元赎回价、最后一期2%票息，以及近期深市同类到期公告仅对最后一期利息扣20%个税所作推算；最终以公司公告和兑付机构口径为准。",sources:[["洽洽上市公告书（115%条款）","https://static.cninfo.com.cn/finalpage/2020-11-17/1208755080.PDF"],["停止交易时间公告","https://paper.cnstock.com/html/2026-09/04/content_2265210.htm"],["2026年半年报","https://static.cninfo.com.cn/finalpage/2026-08-25/1225496055.PDF"],["9月4日行情快照","https://bond.stockstar.com/RB2026090400028480.shtml"],["深市同类扣税实例","https://static.cninfo.com.cn/finalpage/2026-07-16/1225427424.PDF"]]}},
  {id:"04",stage:"等待深度研究",kind:"转债下修",brief:"从完整事件链和失败后的回撤出发，评估下修博弈是否形成非对称结构。",questions:["股东会通过概率","可能下修价格区间","下修失败或不及预期的回撤","信用风险与赔率补偿"]},
  {id:"05",stage:"快速排除已完成",kind:"控制权变更",brief:"用价格和转股溢价率先做防守筛查，不因控制权变更标签自动进入深度研究。",questions:["价格160+","转股溢价15%+","缺乏清晰下行锚","无需继续消耗研究时间"],research:{verdict:"排除",tone:"negative",asOf:"采用你的个案反馈",thesis:"你指出优彩转债价格160元以上、转股溢价率15%以上，防守很难。即使控制权变更值得作为事件标签观察，也不足以抵消高价格暴露；这一案例应作为‘先看概率分布、再看故事’的快速排除样本。",metrics:[["研究动作","停止"],["核心原因","下行锚不足"],["保留价值","快速排除规则"]],facts:["控制权变更是催化标签，不是收益保证。","价格与转股溢价共同决定当前结构；高价转债不能因事件题材自动视为低风险。"],scenarios:[["不利路径","事件终止或正股下跌","高价与溢价可能同时压缩，回撤没有清晰截断。"],["有利路径","控制权交易带来正股上涨","存在收益可能，但不足以把当前结构归入高安全套利。"]],trigger:"只有当价格显著回落、出现新的刚性退出权，或事件条款把下行重新截断时，才重新进入线索池。",uncertainty:"这是基于价格结构的快速排除，不代表对控制权交易后续方向作判断。",sources:[["公司筹划控制权变更公告","https://static.cninfo.com.cn/finalpage/2026-09-04/1225547328.PDF"]]}}
];

function loadJson(key){try{return JSON.parse(localStorage.getItem(key))||{}}catch{return {}}}
function saveReviews(){localStorage.setItem(storageKey,JSON.stringify(reviews));updateDashboard();renderCases()}
function saveCaseReviews(){localStorage.setItem(caseStorageKey,JSON.stringify(caseReviews))}
function visibleSignals(){return signals.filter(item=>{const d=reviews[item.id]?.decision;if(activeFilter==="all")return true;if(activeFilter==="pending")return !d;return d===activeFilter})}

function renderSignals(){const visible=visibleSignals();document.querySelector("#emptyState").hidden=visible.length>0;document.querySelector("#signalList").innerHTML=visible.map(signalCard).join("");bindCardEvents()}
function signalCard(item){const review=reviews[item.id]||{};const reviewed=Boolean(review.decision);return `<article class="signal-card ${reviewed?"reviewed":""}" data-id="${item.id}">
  <div class="signal-index"><span>${item.id}</span><i class="review-mark">${reviewed?"已审":"待审"}</i></div><div class="signal-content">
  <header class="signal-title"><div><span class="tag">${item.tag}</span><h3>${item.instrument}</h3><p>${item.code} · ${item.event}</p></div><div class="ai-badge ${item.aiDecision}"><span>AI建议</span><strong>${item.aiLabel}</strong><small>${item.confidence}</small></div></header>
  <div class="signal-data">${item.data}</div><div class="analysis-grid"><div><span>为什么进入视野</span><p>${item.summary}</p></div><div><span>当前疑点</span><p>${item.caution}</p></div></div>
  <div class="source-row"><a href="${item.source}" target="_blank" rel="noreferrer">${item.sourceLabel} ↗</a>${item.official?`<a href="${item.official}" target="_blank" rel="noreferrer">公司公告 ↗</a>`:""}</div>
  <div class="human-review"><span class="review-label">你的判断</span><div class="decision-group" role="group" aria-label="你对${item.instrument}的判断">${decisionOptions.map(([value,label])=>`<button type="button" data-decision="${value}" class="decision ${review.decision===value?"selected":""}">${label}</button>`).join("")}</div>
  <div class="review-note"><select aria-label="选择判断原因">${reasonOptions.map(reason=>`<option ${review.reason===reason?"selected":""}>${reason}</option>`).join("")}</select><textarea maxlength="280" aria-label="补充你的判断" placeholder="无论选择哪一项，都可以说两句：为什么这样判断？我忽略了什么？">${escapeHtml(review.note||"")}</textarea></div></div></div></article>`}

function bindCardEvents(){document.querySelectorAll(".signal-card").forEach(card=>{const id=card.dataset.id;card.querySelectorAll("[data-decision]").forEach(button=>button.addEventListener("click",()=>{reviews[id]={...(reviews[id]||{}),decision:button.dataset.decision};saveReviews();renderSignals();showToast("判断已保存在当前浏览器")}));card.querySelector("select").addEventListener("change",event=>{reviews[id]={...(reviews[id]||{}),reason:event.target.value};saveReviews()});card.querySelector("textarea").addEventListener("change",event=>{reviews[id]={...(reviews[id]||{}),note:event.target.value.trim()};saveReviews()})})}

function updateDashboard(){const decisions=signals.map(x=>reviews[x.id]?.decision).filter(Boolean);const count=key=>decisions.filter(x=>x===key).length;const reviewed=decisions.length;document.querySelector("#progressText").textContent=`${reviewed} / ${signals.length}`;document.querySelector("#progressBar").style.width=`${reviewed/signals.length*100}%`;document.querySelector("#metricTotal").textContent=signals.length;document.querySelector("#metricPending").textContent=signals.length-reviewed;document.querySelector("#metricResearch").textContent=count("research");document.querySelector("#metricWatch").textContent=count("watch")+count("unclear");document.querySelector("#metricReject").textContent=count("reject")}

function researchDraft(r){if(!r)return `<div class="pending-research"><strong>研究稿尚未发布</strong><p>完成公告、数据和情景核查后，这里会显示研究结论、事实依据、收益结构、悲观情景、失效条件和来源。</p></div>`;return `<section class="research-draft"><div class="research-verdict ${r.tone}"><div><span>AI阶段判断 · ${r.asOf}</span><strong>${r.verdict}</strong></div><p>${r.thesis}</p></div><div class="research-metrics">${r.metrics.map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join("")}</div><div class="research-columns"><div><h4>已核实事实</h4><ul>${r.facts.map(x=>`<li>${x}</li>`).join("")}</ul></div><div><h4>价格触发条件</h4><p>${r.trigger}</p><div class="uncertainty">${r.uncertainty}</div></div></div><div class="scenario-table"><div class="scenario-head"><span>概率位置</span><span>触发条件</span><span>结果</span></div>${r.scenarios.map(row=>`<div><strong>${row[0]}</strong><span>${row[1]}</span><p>${row[2]}</p></div>`).join("")}</div><div class="research-sources"><span>事实来源</span>${r.sources.map(([label,url])=>`<a href="${url}" target="_blank" rel="noreferrer">${label} ↗</a>`).join("")}</div></section>`}
function renderCases(){document.querySelector("#caseList").innerHTML=casePlans.map(plan=>{const item=signals.find(x=>x.id===plan.id);const feedback=caseReviews[plan.id]||{};return `<article class="case-card" data-case-id="${plan.id}"><header><div><span class="tag">${plan.kind}</span><h3>${item.instrument}</h3><p>${item.code}</p></div><span class="status-pill ${plan.research?"":"working"}">${plan.stage}</span></header><div class="case-brief"><span>本轮研究任务</span><p>${plan.brief}</p></div><div class="research-checklist">${plan.questions.map((q,i)=>`<div><span>${String(i+1).padStart(2,"0")}</span>${q}</div>`).join("")}</div>${researchDraft(plan.research)}<div class="case-feedback"><span class="review-label">你的研究反馈</span><div class="verdict-group" role="group" aria-label="你对${item.instrument}研究稿的反馈">${[["agree","认可"],["partial","部分认可"],["disagree","不认可"],["unknown","暂时无法判断"]].map(([v,l])=>`<button type="button" data-verdict="${v}" class="decision ${feedback.verdict===v?"selected":""}">${l}</button>`).join("")}</div><textarea data-field="view" maxlength="600" placeholder="我的看法：同意或不同意哪里？最担心什么？">${escapeHtml(feedback.view||"")}</textarea><textarea data-field="question" maxlength="400" placeholder="还需要继续查什么？（可选）">${escapeHtml(feedback.question||"")}</textarea><button type="button" class="case-copy" data-copy-case="${plan.id}">复制这份研究反馈</button></div></article>`}).join("");bindCaseEvents()}

function bindCaseEvents(){document.querySelectorAll(".case-card").forEach(card=>{const id=card.dataset.caseId;card.querySelectorAll("[data-verdict]").forEach(button=>button.addEventListener("click",()=>{caseReviews[id]={...(caseReviews[id]||{}),verdict:button.dataset.verdict};saveCaseReviews();renderCases();showToast("研究反馈已保存")}));card.querySelectorAll("textarea[data-field]").forEach(area=>area.addEventListener("change",event=>{caseReviews[id]={...(caseReviews[id]||{}),[event.target.dataset.field]:event.target.value.trim()};saveCaseReviews()}));card.querySelector("[data-copy-case]").addEventListener("click",()=>copyText(caseFeedbackText(id),"这份研究反馈已复制"))})}

function feedbackText(){return `套利研究系统｜2026-09-04 第2轮初审反馈\n${signals.map(item=>{const review=reviews[item.id];if(!review?.decision)return `${item.id} ${item.instrument}：未审阅`;const label=decisionOptions.find(x=>x[0]===review.decision)?.[1]||review.decision;const extras=[review.reason&&review.reason!=="未选择原因"?review.reason:"",review.note||""].filter(Boolean).join("；");return `${item.id} ${item.instrument}：${label}${extras?`（${extras}）`:""}`}).join("\n")}`}
function caseFeedbackText(id){const plan=casePlans.find(x=>x.id===id);const item=signals.find(x=>x.id===id);const feedback=caseReviews[id]||{};const labels={agree:"认可",partial:"部分认可",disagree:"不认可",unknown:"暂时无法判断"};return `套利研究系统｜第2轮个案反馈\n标的：${item.instrument}\n研究状态：${plan.stage}\n总体判断：${labels[feedback.verdict]||"未选择"}\n我的看法：${feedback.view||"未填写"}\n还需要研究：${feedback.question||"未填写"}`}
async function copyText(value,message){try{await navigator.clipboard.writeText(value);showToast(message)}catch{const area=document.createElement("textarea");area.value=value;document.body.appendChild(area);area.select();document.execCommand("copy");area.remove();showToast(message)}}
function escapeHtml(value){return value.replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]))}
let toastTimer;function showToast(message){const toast=document.querySelector("#toast");toast.textContent=message;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2200)}

document.querySelectorAll(".nav-item").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x===button));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active-view",x.id===button.dataset.target));document.querySelector("#pageTitle").textContent=button.textContent.replace(/^\d+/,"").trim();if(button.dataset.target==="cases")renderCases();window.scrollTo({top:0,behavior:"smooth"})}));
document.querySelectorAll(".filter").forEach(button=>button.addEventListener("click",()=>{activeFilter=button.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===button));renderSignals()}));
document.querySelector("#copyFeedback").addEventListener("click",()=>copyText(feedbackText(),"初审反馈已复制，可以粘贴到对话中"));
updateDashboard();renderSignals();renderCases();
